# .github/workflows/mirror.yml

name: Mirror Repo to Personal

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Push to personal repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git remote add mirror https://sasamile:${{ secrets.TOKEN_PERSONAL }}@github.com/sasamile/client-software-mirro.git
          git push --mirror mirror
